# PostgreSQL (Supabase)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?user=postgres.pqdghhsenngbwinmruku&password=Mercadoluis20060
spring.datasource.username=postgres
spring.datasource.password=Mercadoluis20060
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=574846360050-npvabi77qgee24hsridn8hm2c085tesd.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

# Correo SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mluisercado@gmail.com
spring.mail.password=uzik beep xock jhon
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Groq API
groq.api.key=

# Servidor
server.port=8080
